### ISSUE TITLE
plugins dont work with python 3.8.1

### ISSUE THREAD

**Issue by lsaadeh** [binhex/documentation#3]
Hi Binhex,

As the head describes, deluge custom plugins don't work as they require python 2.6 or 2.7
The current version on the docker image is 3.8.1, is it possible to downgrade it or create another stream for backward compatibility?

https://dev.deluge-torrent.org/wiki/Plugins

**Comment by binhex** [comment]
no thats not possible, the base os i use is a rolling distro so going backwards is difficult. there is also the problem that the latest version of deluge only works with python 3.x, and of course the fact that python 2.x is now end of life and not receiving any security updates.

python 3.x is the present and future, so all i can recommend is you raise issues on the relevant plugin maintainers repos and get them to update their code to support python 3.x.

p.s. you are posting an issue on the documentation repo, not deluge.
