### ISSUE TITLE
Strange issue accessing GUI

### ISSUE THREAD

**Issue by drego05** [binhex/documentation#4]
I feel bad that I'm the only one that's having an issue, so it's definitely something with my configuration --- but it's strange and I've been seeing it everything I try to load something up behind the PIA connection. We'll say your image because that's what I'm using here.  I know the image is good, it loads up fine for me -- and I've made sure to enter my local network, and make sure I've entered it correctly, but I can ONLY load the GUI from the actual host computer that's running docker and this container. If I remote into the host computer, load up a browser - localhost:8112 - I can hit it no problem. I can't get it from ANY other computer on my local network. I've noticed that from other container running through a VPN connection. Any other services I have running in container, I can get to via hostname or IP followed by the port - but for some reason, I can only hit the GUI for Deluge on the host machine only. Have you seen this before from anyone else?

**Comment by elynch303** [comment]
if your host is windows the is is that your firewall is blocking it
